### ISSUE TITLE
ClassNotFoundException AtomicfuKotlinGradleSubplugin$AtomicfuKotlinGradleExtension

### ISSUE THREAD

**Issue by lppedd** [Kotlin/kotlinx-atomicfu#399]
AtomicFU 0.23.2 with Kotlin 1.9.22.
Happens when importing changes in the IDE, or when attempting to execute any Gradle task.

```
java.lang.NoClassDefFoundError: org/jetbrains/kotlinx/atomicfu/gradle/AtomicfuKotlinGradleSubplugin$AtomicfuKotlinGradleExtension
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.applyAtomicfuCompilerPlugin(AtomicFUGradlePlugin.kt:79)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePluginKt.access$applyAtomicfuCompilerPlugin(AtomicFUGradlePlugin.kt:1)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePlugin.apply(AtomicFUGradlePlugin.kt:48)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUGradlePlugin.apply(AtomicFUGradlePlugin.kt:42)
	...
	at Program.execute(Unknown Source)
	...
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlinx.atomicfu.gradle.AtomicfuKotlinGradleSubplugin$AtomicfuKotlinGradleExtension
	... 214 more
```

**Comment by lppedd** [comment]
@fzhinkin sure, will come up with a repro soon. Seems like I'm the only one experiencing it, so it would be cool to understand where I'm breaking it.

**Comment by willflier** [comment]
I also encountered this issue when upgrading from 0.32.1 to 0.32.2.

**Comment by lppedd** [comment]
Are you using some third party Gradle plugin?  
Just to match what I have.

**Comment by m-sasha** [comment]
Also experiencing this in [Compose Multiplatform](https://github.com/JetBrains/compose-multiplatform-core).

**Comment by lppedd** [comment]
The workaround seems to be working. Thanks @m-sasha

**Comment by fzhinkin** [comment]
@m-sasha thanks! 

The reproducer:
```
git clone https://github.com/JetBrains/compose-multiplatform-core.git --depth=1 -b v1.6.0-dev1405
./jbdeps/android-sdk/downloadAndroidSdk
sed -i -e 's@atomicFu = "0.23.1"@atomicFu = "0.23.2"@' ./gradle/libs.versions.toml
./gradlew :compose:animation:animation --stacktrace
```

**Comment by mvicsokolova** [comment]
I was investigating this issue and found out that the version of atomicfu complier plugin is not resolved in the configuration of `compose`.
According to our last solution (#386), `atomicfu-gradle-plugin` provides a transitive atomicfu compiler plugin dependency and relies on the gradle version resolution. So, we provide compiler plugin with the lowest version and expect it to be resolved into the highest version present on the user's classpath. 

```
runtimeOnly "org.jetbrains.kotlin:atomicfu:1.6.21"
``` 

I made it work by providing the higher version in the code above, but yet could not get the core reason of the problem.

@willflier, would you be so kind to provide your simple Kotlin Native reproducer, so that it would be easier to debug the configuration? I failed to reproduce this on a Native only project myself 👀

**Comment by mvicsokolova** [comment]
This issue is fixed since `0.24.0` release
